### ISSUE TITLE
Same split image for every split. Region saving.

### ISSUE THREAD

**Issue by Mokaygee** [Toufool/Auto-Split#10]
I love this idea!

Issue 1: It would be nice if there was an option to split indefinitely any time any single image is spotted in the region. With my game as it is, I have the same autosplit image for all my splits. Not a huge issue but a nice optimisation.

Issue 2: When I close and reopen autosplitter, it save the dimensions and I assume position of the region in OBS, but it does not exactly save the region fully. Every time I close autosplitter, I am to select the region every time.

The second issue is clearly more important, but I can think of a few games that have exactly the same save screen and therefore some sort of indefinite split option for a single image would be nice too.

**Comment by Toufool** [comment]
I'd definitely prioritize issue 2 over issue 1. I have most settings saved upon reopen, but as you have noted, region is not one of these. I do think that the window you were using as the capture region will need to be open before you open AutoSplit for it to re-load properly, though.

**Comment by Mokaygee** [comment]
A half way house would be to add co-ordinates of the position of the region aswell as width and height. That would be an easy fix, and for people who never change the window size of OBS we could simply remember or write down our numbers.

**Comment by Toufool** [comment]
Issue 2 has been fixed in [v1.1](https://github.com/Toufool/Auto-Split/releases/tag/v1.1). There are now coordinate values and as long as you still have the window open and the window size has not changed, it should re-open the same capture region.

**Comment by Toufool** [comment]
Issue 1 has been added as a feature in [v1.3](https://github.com/Toufool/Auto-Split/releases/tag/v1.3). You now have the option to loop split images, so you can just have one image in the split image folder and loop over that one over and over.
