### ISSUE TITLE
Pause time does not apply to first split

### ISSUE THREAD

**Issue by strength** [Toufool/Auto-Split#11]
The first split image I have is a full black screen, but right after the run starts there is also a black screen. This would be ignored if pause time applied to the first split but it doesn't seem to, so it autosplits a second after my run starts and I have to use undo split to line it back up.

**Comment by Toufool** [comment]
we plan to include "dummy splits" in the next version. In this case, I believe this would solve your issue. You could use your first split as a black image and flag is as a dummy split (it wont hit your split hotkey) and then have it pause for however long you would like, as custom pause times per split image also plan to be implemented.

**Comment by Toufool** [comment]
The option to flag splits as dummy splits has been added in [v1.1](https://github.com/Toufool/Auto-Split/releases/tag/v1.1).
