### ISSUE TITLE
start image pause time remaining all out of whack

### ISSUE THREAD

**Issue by Toufool** [Toufool/Auto-Split#114]
I don't have a repro for this atm. But: 
![image](https://user-images.githubusercontent.com/37423484/143725049-08459d27-5672-4a41-8bc5-b94a4a96b8a6.png)

**Comment by Avasam** [comment]
I *think* this is fixed by #72 Or is just a cincidence

**Comment by Toufool** [comment]
@Avasam  I think I fixed this here? https://github.com/Toufool/Auto-Split/commit/3cb2aa6d75394ba64125bd0bccad0d126bbb0c0a It was entering the pause loop even if there was no pause. If there was no start hotkey, and was not auto controlled, it was entering the if statement that changed the pause before loading start image label. This commit also fixed an issue where it was allowing the start image to constantly start auto-split and open endless amounts of "no reset hotkey" or "no pause hotkey" set errors so I just made a check to make sure ALL of those were set before it even loads a start image.
