### ISSUE TITLE
Can't bind side mouse buttons

### ISSUE THREAD

**Issue by MasterXdX** [Toufool/Auto-Split#123]
I have 2 side buttons on my mouse that I use for start / split and reset.
However I can't bind them on auto splitter, is there any fix for it ?

**Comment by Avasam** [comment]
I know you found a workaround by remapping. But let's keep this open. It's something I'd like to give a shot at implementing down the line. Although we'll need to write a wrapper around the `keyboard` and `mouse` libraries to combine them.
