### ISSUE TITLE
Different metrics for image similarity

### ISSUE THREAD

**Issue by thomasneff** [Toufool/Auto-Split#14]
Hi!

First of all - nice job with the autosplitter, I haven't tested it much, but for many images it seems to work pretty well. 

A problem with computing an image similarity using the L2 norm between images is that it's very sensitive to geometric transformations (rotation, translation...) since it simply compares pixel-wise, without taking larger contexts into account (i.e. moving an image just by a few pixels can result in a similarity result that's completely wrong, given enough high-frequency content in the compared images). Additionally, it is also very sensitive to global lighting changes, such as additive noise or a simple shift in mean color, which is very common for different setups due to e.g. different capture cards.

As an example, if you wanted to measure similarity to the loading screen images of the Crash N. Sane Trilogy, which consists of mostly black pixels, you would have an issue there, as you can't distinguish reliably between transitions (black screens) and the loading screen. If you restrict your capture region to just the "LOADING" part, the L2 norm will have issues due to it not being aligned perfectly, in addition to the "LOADING" text being animated as well. 

I recommend to include multiple different similarity metrics, which users can choose from, to select the one that's the most stable and provides the least amount of false positives. 
This stackoverflow answer provides a nice summary of metrics:
[https://stackoverflow.com/a/11541587](https://stackoverflow.com/a/11541587)

For the Crash N. Sane Trilogy load remover, I compared histograms of patches to detect the load screens of the game (without detecting black screens), which worked very well. Template matching and/or feature matching might also work fine, but they might not work in real-time.  

Maybe even a combination of multiple metrics could be nice, if the performance would still be reasonable. Ideally, a community would just provide a folder of images for their game, which can then be used by everyone, with the tool being robust enough against small differences in capture setup/capture region.

If you're not that familiar with that stuff about the similarity metrics, I can also play around with that and send you a pull request.

**Comment by Faschz** [comment]
During development comparing histograms was one of the methods we had initially used to calculate the similarity. But, the reason we chose to move over to sum of square differences is mostly a performance choice. Now that the release is out, I haven't heard anyone having performance issues and would not be opposed to including histogram comparison using Bhattacharyya Distance.

I also happened to do template matching (Again using square differences) on opencv, but I felt that was better for a future update with more complicated options for the user. Perhaps in the same future update as image masking. I'm not sure about the real time feasibility with that at the moment.

For now, I think other users have suggested implementing positional coordinates similar to the width/height boxes. I think that will help users a lot with their misaligned images temporarily until other metrics are implemented.

Thanks for the suggestion, we'll definitely keep it in mind.

**Comment by okiyama** [comment]
I came here to make this exact suggestion. I'd like to also toss on the possibility of using image hashing, for example: https://pypi.org/project/ImageHash/ which has aHash, pHash, dHash and wHash all implemented out of the box.

I used pHash long ago to compare pictures of Magic the Gathering cards and it worked pretty well for that case. It sounds like it may not be performant enough though based off this page: http://www.hackerfactor.com/blog/index.php?/archives/529-Kind-of-Like-That.html
For my use case it was fine, but that wasn't real-time.

**Comment by Faschz** [comment]
After brief testing of pHash, it isn't as performance heavy as described there. In fact one of the comments mentions they were getting over 5000 hashes per second. Using imagehash, with converting the images we are capturing to PIL images, it takes ~4 milliseconds on average per comparison on the device I'm using. That is well within the range of our goal of 60 fps. In comparison, L2 Norm takes ~0.05 ms and histogram comparison ~1.3 ms

**Comment by okiyama** [comment]
That's very good to hear! I expect pHash could do a better job than what you've got now, obviously at the price of performance. So branding it as an optional "enhanced precision" or something like that could work well. I'm glad it's not immediately out of the question though.

**Comment by Toufool** [comment]
Histograms and pHash have been added as comparison methods in [v1.1](https://github.com/Toufool/Auto-Split/releases/tag/v1.1)
