### ISSUE TITLE
Feature Request: On split image, increment a number in .txt format

### ISSUE THREAD

**Issue by davidvkimball** [Toufool/Auto-Split#145]
I would love a feature where whenever a split image comes out, add +1 to a number so I can print it on OBS.

For example: 

In my Smash Bros. Melee speedrun I'm doing, I need to keep track of 1,000 matches (I know it's dumb), so I'm using AutoSplit to hit a key every time "Game!" appears, and then passing that onto another piece of software that uses a very high amount of CPU usage, which adds "+1" to a counter that is displayed in OBS.

I would love it if AutoSplit could automate this by just doing it itself.

Happy to answer any questions!

**Comment by Avasam** [comment]
There's a couple of OBS counter plugins with hotkey support you could try. This will also solve having to use an external program.
I found the following:
- https://obsproject.com/forum/resources/counter-text-source-based-for-up-to-4-text-sources.1085/
- https://obsproject.com/forum/resources/tally-counter.989/

Any of those two should allow you to use AutoSplit as-is.

**Comment by davidvkimball** [comment]
> There's a couple of OBS counter plugins and scripts with hotkey support you could try. This will also solve having to use an external program. I found the following:
> 
>     * https://obsproject.com/forum/resources/counter-text-source-based-for-up-to-4-text-sources.1085/ (Python)
> 
>     * https://obsproject.com/forum/resources/tally-counter.989/ (and a LUA alternative if you don't want to install Python: https://gist.github.com/tid-kijyun/477c723ea42d22903ebe6b6cee3f77a1 )
> 
>     * https://github.com/fchorney/obs-persistent-counter (Lua)
> 
>     * https://github.com/RetroTGaming/OBS-Count-Things (Python)
> 
> 
> Any of those should allow you to use AutoSplit as-is. LiveSplit also has a Counter component.

Hey Avasam! Thanks for t he response. 

Lots of really cool options - thank you. A friend ended up making a pretty simple AutoHotKey script for me to use which works.

I'm curious, though, how do you use the LiveSplit Counter component? I've combed through settings and did some Googling and can't seem to find anything about it.

**Comment by Avasam** [comment]
You can configure a hotkey. So if you use AutoSplit without the livesplit integration, you can just make your "Split" hotkey in AutoSplit the same as the "Increment Counter" one in LiveSplit.
![image](https://user-images.githubusercontent.com/1350584/173199289-66285395-7ec7-42ee-afa6-a281abc4375c.png)

**Comment by davidvkimball** [comment]
> 

This is a perfect solution! Thank you! I didn't realize you could get a counter add-on for LiveSplit. It works great.
