### ISSUE TITLE
Different similarity per split image

### ISSUE THREAD

**Issue by xwmtp** [Toufool/Auto-Split#15]
Great job on the tool, I love it!

The biggest improvement for me would definitely be being able to select a specific similarity per split image. I know this is in the 'known limitations', but I wanted to make an issue for it to be sure. In the game I play (Ocarina of Time), many cutscenes aren't pre-rendered and might be slightly different everytime. For those I'd have to put a lower similarity than more stable cues like a white fade.

Thanks for the good work!

**Comment by Toufool** [comment]
This feature has been added in [v1.1](https://github.com/Toufool/Auto-Split/releases/tag/v1.1)
