### ISSUE TITLE
Angular brackets in file name is forbidden in Windows

### ISSUE THREAD

**Issue by zalgo3** [Toufool/Auto-Split#158]
> A different comparison method can be specified with their 0-base index between angular brackets <>:
> <0>: L2 Norm
> <1>: Histogram
> <2>: Perceptual Hash

Angular brackets <> are forbidden in Windows, so we should use other symbols for this purpose.
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

**Comment by Avasam** [comment]
Already fixed: https://github.com/Avasam/Auto-Split/releases/tag/v2.0.0-alpha.5
