### ISSUE TITLE
Window is tiny

### ISSUE THREAD

**Issue by BGP19000** [Toufool/Auto-Split#16]
For me, the window is tiny. Probably because I have a 4k Screen. So I go to drag the window bigger, but I cannot :( However, this is useable, just really annoying. 
![image](https://user-images.githubusercontent.com/39221078/56160509-3f7c1700-5fbf-11e9-98aa-15ae2d7ded3d.png)

**Comment by flagrama** [comment]
Right click EXE > Properties > Compatibility tab > Change High DPI Settings button > Check "Override high DPI scaling behaviour. Scaling performed by:" > Choose "System" in the drop down.

This is what I do for EmoTracker, I assume it should work similarly here. It's something I have to do fairly often.

**Comment by BGP19000** [comment]
Nice! I have had this problem on a few programs recently, and this fixed it :)
