### ISSUE TITLE
Optimization of current norm metric

### ISSUE THREAD

**Issue by crazyjesse** [Toufool/Auto-Split#17]
Hey guys, I was curious about the convention you use for image check, and if I'm not mistaken, the relevant code is:

`           error = cv2.norm(split_image, sct_img, cv2.NORM_L2) `
`            max_error = 255 * 255`
`            for dimension in split_image.shape:`
`                max_error *= dimension`
`            max_error = max_error ** 0.5`
`            similarity = 1 - (error / max_error)`

I'm not sure if you realise, but most this can be summarised much more succinctly as 

`error = cv2.norm(split_image, sct_img, cv2.NORM_L2)`
`max_error = (split_image.size ** 0.5) * 255 `
`similarity = 1 - (error / max_error)`

as `.size` computes the product of the individual components of `.shape` and the second optimization is that the square root of 255*255 is 255, no need to reassign it every time. Hopefully this shaves off a few cycles :-P

Sorry for not doing a branch/pull request, it didn't seem worth it for a one-line change.

Cheers,
crazyjesse

**Comment by Toufool** [comment]
Thanks for the catch. This has been changed since it definitely looks cleaner.
