### ISSUE TITLE
Can't select region on a third monitor

### ISSUE THREAD

**Issue by Miltrivd** [Toufool/Auto-Split#18]
I just started checking the tool and I have 3 monitors on this setup: 3 - 1 - 2. I can only select region on the first and second monitor (so center and right side) but not on the left side.

For now I'll just switch OBS to the second monitor but it'd be ideal if I could put the window where it is now.

**Comment by Toufool** [comment]
I haven't tested with 3 monitors, so I can't off the top of my head provide a solution to dragging the selection region for the 3rd monitor. However, once the region is selected, you should be able to freely move that window (OBS) to the third monitor without it changing the capture region.

**Comment by Miltrivd** [comment]
That's great, didn't think about that. Works perfectly.

**Comment by Faschz** [comment]
This will actually be fixed hopefully in the next release. For anyone having this issue, that is one way to select the region or moving any additional monitors to the right or below the main monitor.

**Comment by Toufool** [comment]
This bug should be fixed in [v1.1](https://github.com/Toufool/Auto-Split/releases/tag/v1.1) Feel free to re-open the issue if it is still an issue in 1.1.
