### ISSUE TITLE
2.0.0: `Undo` and `Skip` buttons are not accessible in the `Paused` state after being `Delayed`

### ISSUE THREAD

**Issue by Toufool** [Toufool/Auto-Split#184]
Delayed State (this is correct)
![image](https://user-images.githubusercontent.com/37423484/198857171-5cf352dc-22f3-4e53-841c-e6524cb945c8.png)

Paused State right after being delayed (Undo and Skip should be re-enabled if appropriate)
![image](https://user-images.githubusercontent.com/37423484/198857185-85630f03-79b5-45e9-9aa1-7d3806f72256.png)

Confirmed this is working in 1.6.1:

Delayed State:
![image](https://user-images.githubusercontent.com/37423484/198857192-94fcb505-90c1-4c7b-aa28-286abeaea95d.png)

Paused state right after being delayed:
![image](https://user-images.githubusercontent.com/37423484/198857211-aaeedc75-e7da-4c3d-8cab-599b7fdeae74.png)

**Comment by Avasam** [comment]
I've also noticed that with both pause and delay together, if an image is an immediate (first frame) match, the delay sometimes won't be triggered.

**Comment by Toufool** [comment]
Confirmed that these buttons are now accessible after a split is delayed and then paused. closing
