### ISSUE TITLE
Specify naming convention for image files

### ISSUE THREAD

**Issue by Miltrivd** [Toufool/Auto-Split#19]
Image files do not accept certain characters, which is not much of an issue but would be nice if a warning is set so the user can be aware.

I had a file name with an umlaut ("23 Brachsenbrüke") and when trying to start the split I had an error saying "All files in split image folder must be valid image files" which was a bit confusing since they all were.

**Comment by Toufool** [comment]
Didn't fix the bug, but I did fix the error message to make it more clear when this error gets thrown https://github.com/Toufool/Auto-Split/commit/a288f65d77ee77b4b5033c25019fe5b4b7a4cc19
