### ISSUE TITLE
Load Time Remover

### ISSUE THREAD

**Issue by VikeStep** [Toufool/Auto-Split#2]
Hello, I've just tried out this tool for Mario Kart 8 Deluxe and it's working really well for splitting at the loading screen. However, I was wondering if there could be a feature in this tool to automatically pause whenever the loading screen shows. Loading times vary a lot in this game (especially between a Digital and Cartridge version), so it would be a lot more useful than automatically splitting.

**Comment by Faschz** [comment]
The plan isn't to use this as a load time remover at the current time.

However, I can propose a solution to potentially use it as is for that. By setting the split key in AutoSplit to the pause key of your timer, it will pause instead. You will need two images per "loading zone", one for the initial pause and another to unpause. Obviously you are foregoing the ability for the program to split in this case. But, if your main goal was to simply remove loading times, that option is out there.

**Comment by ROMaster2** [comment]
If you would like a load remover, get in touch with me on this repository. https://github.com/ROMaster2/LiveSplit.VideoAutoSplit

**Comment by VikeStep** [comment]
Thanks for the workaround, I can confirm that solution works :D I suppose I created this issue as more of a suggestion in case you thought it could go in, but if not I'm fine with this issue being closed.
