### ISSUE TITLE
Splits do not work with some keys

### ISSUE THREAD

**Issue by Losspeedrunning** [Toufool/Auto-Split#20]
![split setup](https://user-images.githubusercontent.com/49699149/56248080-36ff0b80-60a7-11e9-8213-0ce623f20646.PNG)

I tried my normal setup and it did not work... When I changed the splitkey to a character (in my case: q) it worked. Maybe you can add this somewhere :)

**Comment by Toufool** [comment]
See https://github.com/Toufool/Auto-Split/issues/8
