### ISSUE TITLE
Save Selected Region Settings

### ISSUE THREAD

**Issue by benstephens56** [Toufool/Auto-Split#21]
Some of the screenshots I have set up are relatively specific and thus require the selected region capture to be in the exact same location. However, currently closing AutoSplit resets the region capture. Setting this up every time I open the program is fine, but it would be neat to be able to save region capture settings and perhaps set up different profiles for different games. Thanks for the hard work, loving this so far!

**Comment by Toufool** [comment]
Region settings now save upon close and re-open in [v1.1](https://github.com/Toufool/Auto-Split/releases/tag/v1.1)
