### ISSUE TITLE
forced shutdown

### ISSUE THREAD

**Issue by zylinderguy** [Toufool/Auto-Split#22]
after closing Autosplitter it throws the follow exception

![fehler](https://user-images.githubusercontent.com/49847794/56477083-f84fc380-64a1-11e9-9737-14bf1fb4c632.jpg)

with the following error code

> Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	AutoSplit.exe
  Anwendungsversion:	0.0.0.0
  Anwendungszeitstempel:	5b8e995f
  Fehlermodulname:	python37.dll
  Fehlermodulversion:	3.7.3150.1013
  Fehlermodulzeitstempel:	5c9954b1
  Ausnahmecode:	c0000005
  Ausnahmeoffset:	000000000005746b
  Betriebsystemversion:	6.1.7601.2.1.0.256.48
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	0678
  Zusatzinformation 2:	06789b0961ef8bfa1077a803026b5b81
  Zusatzinformation 3:	fe6a
  Zusatzinformation 4:	fe6ab864df88c9efe17f3c17ac16ecbc

kind regards

**Comment by zylinderguy** [comment]
nobody an idea whats the cause for this problem?!

**Comment by Toufool** [comment]
This seems to be an issue for some people and not others. It's something I definitely want to fix, I'm just not 100% sure on how to reproduce this consistently yet. Are you on windows 7?

**Comment by Toufool** [comment]
Idk if this is environmental or what, but I haven't heard any reports of this issue in quite some time. gonna close.
