### ISSUE TITLE
Feature request: split delay

### ISSUE THREAD

**Issue by OoDeeR** [Toufool/Auto-Split#23]
This is a simple feature request that is probably easy to implement.
Now that custom image settings are a thing, a very useful feature  would be a parameter for delay.
That way you could customize the autosplitter to work with existing splits, e.g. ones that have utilized audio cues thus far.
A possible format could be: 001_SplitName\_(0.9)\_[10]\_{2.2}.png (split image with a threshold of 0.9, a pause time of 10 seconds and a split delay of 2.2 seconds after the match).

**Comment by Toufool** [comment]
This is already a feature that exists in LiveSplit. 
Right click -> Settings -> Hotkey Delay (Seconds)

**Comment by OoDeeR** [comment]
Thanks for pointing that out, I actually didn't know about that feature. However, it looks like a global setting and is not very useful for what I was suggesting - unless I'm missing something.
My suggestion was to have the option to customize individual splits to make the autosplitter compatible with existing split files. After thinking about my personal use cases, I'll probably use fresh splits anyway, but I think the option would be useful for a few people for the aforementioned purpose.

**Comment by Toufool** [comment]
I realize that the option to customize the split delay on a per split basis isn't something that's possible in LiveSplit, but its a global setting as you said. I'm going to reopen this and keep it as an enhancement for when I come back to work on this more.

**Comment by Toufool** [comment]
This has been implemented in [v1.3](https://github.com/Toufool/Auto-Split/releases/tag/v1.3)
