### ISSUE TITLE
Wrong custom checkbox is saved upon shutdown

### ISSUE THREAD

**Issue by slashinfty** [Toufool/Auto-Split#24]
If "Custom thresholds" is checked when AutoSplit is shutdown, it opens with "Custom pause times" checked. Conversely, if "Custom pause times" is checked when AutoSplit is shutdown, it opens with "Custom thresholds" checked.

If both are checked, they'll both be checked on restart, and if both are unchecked, they'll both be unchecked on restart.

Giving the code a quick browse, I think I found the error, and it resides [here](https://github.com/Toufool/Auto-Split/blob/master/src/AutoSplit.py#L1054) and [here](https://github.com/Toufool/Auto-Split/blob/master/src/AutoSplit.py#L1061) - namely, the reverse ordering of `self.custom_pause_times_setting` and `self.custom_thresholds_setting` in the save and load arrays.

Cheers!

**Comment by Toufool** [comment]
Appreciate the catch. This has been changed and fixed in v1.2.0

**Comment by Toufool** [comment]
This has been fixed in [v1.2](https://github.com/Toufool/Auto-Split/releases/tag/v1.2)
