### ISSUE TITLE
Numlock-on keys are linked to numlock-off keys when using them as hotkeys

### ISSUE THREAD

**Issue by Innnocent** [Toufool/Auto-Split#25]
I noticed that the tool switches threw Split Images when using the Arrow up and Arrow down Key which is unpractical for playing games that use the Arrow Keys to move it would be good if there would be an option to maybe change these Shortcuts

**Comment by Toufool** [comment]
There's nothing in the program that ties Arrow up and Arrow down to switching through split images. What are your hotkeys set as in AutoSplit?

**Comment by Innnocent** [comment]
I tried multible ones but at the moment its like this and only when the Autosplitter is started it changes threw the Splits
![2019-04-27 16_17_09-AutoSplit](https://user-images.githubusercontent.com/50047039/56850833-3583dd80-6908-11e9-962d-62267f6501ab.png)

**Comment by Innnocent** [comment]
never mind it was the problem with my splits and i apparently only tested it as i had the wrong splits

**Comment by Toufool** [comment]
I think I found the issue here. Numbers correspond to other keys on the numpad. It seems as if you set your hotkey as 0-9, you can also use their corresponding keys as that hotkey and vice-versa (for example, 2 is linked to arrow down). I'm going to rename the issue here and tag this as a bug.
