### ISSUE TITLE
Option for different comparison methods per split

### ISSUE THREAD

**Issue by DrDevinRX** [Toufool/Auto-Split#26]
Would this be possible to add different comparison methods per split? As you point out in the readme, pHash is not great at detecting masked images. However, I find it much better for some splits where Histogram will give a 0.97 confidence on a false positive and pHash will give a more conservative 0.70.

Another question, would it be possible for it to tell the difference between two splits such as splitting on a HUD element disappearing rather than it appearing?

**Comment by Avasam** [comment]
This should totally be feasible to implement. Although a nice code cleanup first would be really beneficial for this, before duplicating the code for reset, split and autostart.

> tell the difference between two splits such as splitting on a HUD element disappearing rather than it appearing
You should be able to use the below {b} tag with a masked image of your UI element.
