### ISSUE TITLE
Feature request: Option to split below a certain threshold

### ISSUE THREAD

**Issue by paulsens** [Toufool/Auto-Split#29]
Hey love your software. We were hoping to use it as a load remover as well, and it certainly has the ability to fire a "pause the timer" hotkey when, say, some region of the screen goes full black, but we would also need the option to send the "unpause the timer" hotkey when "this region is NOT full black" is true following the previous positive comparison. So really all I'm asking for is to have the option of firing a hotkey when the similarity is BELOW some threshold, not just above.

**Comment by paulsens** [comment]
I went ahead and wrote the code for this myself, I appreciate your coding style, very easy to understand.

**Comment by Toufool** [comment]
Sorry for late response - glad you were able to get that to work for you. I plan to work on this, eventually lol. I think it'd be a neat feature, and has been asked about before.

**Comment by Toufool** [comment]
Going to close this and provide updates in this issue, as its basically a duplicate: https://github.com/Toufool/Auto-Split/issues/40
