### ISSUE TITLE
Autosplit launches without saved settings when launched via Windows search

### ISSUE THREAD

**Issue by dshepsis** [Toufool/Auto-Split#32]
On Windows 10, when I open the program by pressing the Windows key and typing "autosplit", then selecting it to run, it opens without any of its saved settings. 
![image](https://user-images.githubusercontent.com/16926704/64492917-a1c40580-d247-11e9-9dc0-5196884d59db.png)

I've checked that this is not a different instance of the executable. When I navigate to the exe file via Windows explorer and double click it, it opens with its saved settings as expected.
![image](https://user-images.githubusercontent.com/16926704/64492928-c91ad280-d247-11e9-918d-546a58e1df79.png)

**Comment by Toufool** [comment]
I was able to reproduce this. I'm not sure exactly how to fix it off the top of my head, but I suggest either creating a desktop shortcut or pinning to your taskbar, as those seem to load settings just fine.

**Comment by bentglasstube** [comment]
it seems likely that windows is not setting the current directory when launched from search, and so autosplit cannot find the settings file.

**Comment by Avasam** [comment]
@Toufool @dshepsis I'm currently using the version from PR #50 . It fixed an issue I was having where the settings were never read. I also can't replicate this bug with that version.

**Comment by Avasam** [comment]
Note this issue also happens with the LiveSplit integration. The default settings location uses the location the app is launched from, not the location of the .exe file itself.
