### ISSUE TITLE
Feature Request: Make custom thresholds optional

### ISSUE THREAD

**Issue by dshepsis** [Toufool/Auto-Split#33]
Currently, as stated in the readme "All images must have a custom threshold if the box is checked."

I would prefer if custom thresholds were not required on all images, as there are only a couple splits for which I find the default threshold (0.9) doesn't work well. I could batch rename my files, but I would prefer if this weren't necessary.

**Comment by Moliman** [comment]
It should be fixed with that [pull request](https://github.com/Toufool/Auto-Split/pull/31)

**Comment by Toufool** [comment]
I think I'm going to leave this as is in master. When there is a custom threshold for a split image and it starts comparison of that image, it places that value in the similarity threshold spinbox in the GUI for clarity. That spinbox value is the value used to compare to the live similarity. (it can even be changed mid-run).  I wouldn't want that spinbox value to stay 0.9 while the custom threshold is 0.85, for example. This is just a design choice I'd like to stick with.

**Comment by dshepsis** [comment]
This isn't just a matter of design choice. The issue is that, if a user makes, say, a few dozen split images, and finds that one of them is consistently reaching .88 similarity but is otherwise fine, they have to lower their default similarity threshold (which could introduce issues with other images) or add a `(0.9)` to every single one of those image files besides the one giving the issue, which is needless tedium, especially if they want to change that default threshold later.

Could you add a second spinbox? Label one of them "Default Threshold" having the same function as the current one, and the other being "Image/Current Threshold" which isn't actually interactive, just shows the current image's similarity threshold (whether or not it's the default value), and is grayed-out unless the "Custom Thresholds" checkbox is checked.
