### ISSUE TITLE
Skipping and undoing splits when using dummy splits causes a desync

### ISSUE THREAD

**Issue by dshepsis** [Toufool/Auto-Split#35]
If my next split image is a dummy split, and it's followed by the real image for that split, and I press the "skip split" hotkey, LiveSplit will move onto the next real split, but AutoSplit will move onto the next image, even though it's the "real image" for the split I just skipped. This causes LiveSplit and AutoSplit to become desynced. This can happen whenever dummy images are used, regardless of the number. This can also happen with dummy splits. 

This can be worked around by using the "skip split" button in AutoSplit, which doesn't affect LiveSplit. This could be an issue during runs however, and makes the process of troubleshooting false splits via video more frustrating.

**Comment by Toufool** [comment]
Grouping dummy splits when skipping/undoing splits has been added in v1.3.
