### ISSUE TITLE
Fix tab order in interface

### ISSUE THREAD

**Issue by dshepsis** [Toufool/Auto-Split#37]
When filling out multiple fields at a time (e.g. the X, Y, Width, and Height fields for a particular source from a note that I have), it's helpful to quickly move between fields by pressing Tab.

In AutoSplit, this is difficult because the tab-order of interface elements defies what one visually expects. This is the actual order:

```
Split Image Folder text field (Not normally selectable)
Live Capture Region checkbox
Similarity Threshold number field
Show live similarity checkbox
Show highest similarity checkbox
Start / Split text field (Not normally selectable)
Undo Split text field (ibid)
Skip Split
Reset
Width
Height
FPS Limit
X
Y
Comparison Method selector
Pause time number field
Custom pause times checkbox
Custom thresholds checkbox
```
Notably, all the buttons in the interface (e.g. Select Region, Align Region, Browse, Take Screenshot) can't be accessed via tab navigation.

Here's a visual explanation:
![Tab order](https://user-images.githubusercontent.com/16926704/64908948-b4b95880-d6d3-11e9-9931-a1e737a6d2b8.png)

**Comment by Toufool** [comment]
tab order has been fixed and will be in the correct order in v1.3
