### ISSUE TITLE
Allow selecting the captured window without changing the region

### ISSUE THREAD

**Issue by dshepsis** [Toufool/Auto-Split#38]
Currently, if you want to change what window is captured (e.g. if you've accidentally opened AutoSplit before the program you want to capture), you have to use the "Select Region" button. If you then click the window you want to capture, you'll get a "Width and height cannot be 0." error. If you click and drag across that window, you'll correctly select it, but you will also modify the captured region's position and dimensions.

Currently, my workaround is to have a text file which contains the x, y, width, and height values for my current recording setup. Whenever I open AutoSplit this way, I have to select the window again, then manually re-enter those dimensions by reading from the text file. This is tedious and unnecessary. 

Restarting AutoSplit with the desired program open does not solve the issue. Once AutoSplit fails to find the window even once, it must be manually reselected as described above.

My preferred solution would be a to add a selector dropdown to the menu which matches the title of the window to be captured, similar to how 'Window Capture" works in OBS.

**Comment by Toufool** [comment]
This feature was added in this commit https://github.com/Toufool/Auto-Split/commit/38d54126e33b709f5294cd331eb9448391667ef8

**Comment by dshepsis** [comment]
This issue should be re-opened. The "select window" button **does** change the region. It selects the entire body of the window clicked on, not including the borders and top bar. This overwrites and existing dimensions you had input, requiring them to be entered again.
