### ISSUE TITLE
Feature Request: Allow the split images to loop until manually stopping the Auto Splitter

### ISSUE THREAD

**Issue by Epic-Doughnut** [Toufool/Auto-Split#39]
Currently, I'm trying to use Auto Split to automatically remove load times by hitting the pause button when it sees a loading screen then hitting it again when it sees the loaded game again. This means I'm only using 2 total split images, and I'd like for the program to be able to loop between them automatically so I don't have to copy and paste them 100 times and number them.

**Comment by Toufool** [comment]
A Loop Split Images option has been added in [v1.3](https://github.com/Toufool/Auto-Split/releases/tag/v1.3)
