### ISSUE TITLE
Feature Request: Allow an image to become active when similarity is met and split when no longer similarity is met

### ISSUE THREAD

**Issue by Alberona** [Toufool/Auto-Split#40]
So I was struggling while trying to get a final split picture in Sly 4 Episode 5 last night. The only thing that is consistent in that frame is the health bar of the boss. However, her health never goes to zero it stays at 1 hit off and then upon last hit the health bar dissapears immediately. I can easily get a picture that gets similarity with her health bar at 1 hp but there is no way to get similarity on the frame she dies with current options. So I was thinking if you could make an option so that the image could be selected upon similarity being hit and then upon there being no more similarity anymore, that's when it splits? That way it would actually be possible to get a split picture there since it could split upon health bar dissapearing

**Comment by Toufool** [comment]
I've added this feature in this commit: https://github.com/Toufool/Auto-Split/commit/39bba0e69257aa2ca1e6b9d75f92558bb208aff9

It will be a {b} flag in the split image file name. The similarity will first go above the threshold, which will do nothing, then will split when it goes below the threshold.
