### ISSUE TITLE
Feature Request: Retroactive Split (i.e. Negative Delay)

### ISSUE THREAD

**Issue by dshepsis** [Toufool/Auto-Split#42]
In some cases, it might be desirable to be able to split a fixed time before a good, consistent image or UI element is displayed on the screen.

For example, in Mario Kart 8 (at least as it was described to me; I don't actually run the game myself), standard IL timing involves stopping/pausing the timer as soon as the finish line is crossed, but there is no clear visual indicator this has happened until a few seconds later when the results screen appears. Because the display can vary greatly at the moment the finish line is crossed, there is no way to provide a consistent image to split at this moment or earlier.

Ideally, AutoSplit would be given a masked image of the "FINISH" text that appears on text later, or of the race results UI, then recognize that image, then split a fixed amount of time in the past, at the moment when the finish line was actually crossed.

In general, this feature could be used any time a split (especially the final split of a run) has no good images until _after_ that split should be made.

Unfortunately, as far as I can tell, LiveSplit does not support retroactive splits or negative delay, and you can only really perform this sort of logic by editing the splits later. That said, maybe you can see a more reasonable way to achieve this. Perhaps this could be done through a LiveSplit component, which might also be a good way to remove the need for Auto-Split to use global hotkeys.

If no such thing can be done, then that's okay. This feature can be manually replicated by letting auto-split work when it works, then manually subtracting a fixed delay from the split files.

**Comment by Toufool** [comment]
I think this would have to include, or be entirely, a livesplit component. Although I understand the need for this, one of AutoSplits main goals was to work for any timer with hotkeys, so I don't really want to put a bunch of time into a specific feature for a specific timer.
