### ISSUE TITLE
Feature Request: Split based on sound

### ISSUE THREAD

**Issue by dshepsis** [Toufool/Auto-Split#43]
Simply, instead of splitting based on the captured image, it might be beneficial to split when the game plays a certain sound effect. OBS supports monitoring the audio of individual sources (i.e. replaying the captured sound to the desktop), so a sound-based auto-splitter could simply listen to desktop audio. It would of course be disrupted if the user was, say, playing background music, but wouldn't be disrupted by a mic, since one would set OBS to only replay the game sound, and not the mic sound.

Sound effects can last much longer than images, so it might be beneficial to have the option to split when the first _n_ milliseconds of a sound file match, rather than waiting until the whole sound is heard. This could also be achieved by the user just cutting the sound files themselves, though.

**Comment by Toufool** [comment]
While this would be a cool feature, I think this would be an entirely new program and not something I would want to spend the time to add as a feature.
