### ISSUE TITLE
Feature Request: Loop Parameter

### ISSUE THREAD

**Issue by Oatflaker** [Toufool/Auto-Split#46]
While nearly all of my split images are the same, I have a couple that are different which makes me unable to use the loop split images feature. I think this feature could be improved if looping was a parameter set in the filename (ex: 001_SplitImage|43| . this would make this split image loop 43 times before moving on to the next image in the folder.)

**Comment by Toufool** [comment]
I really like this idea and am going to implement it. Played around with it last night and was easy to get working, but making skip/undo splits work along with it was a little bit of a struggle. It's also going to need some visibility on the GUI on which loop the split image is currently on.

**Comment by Toufool** [comment]
I've added this as a feature in this commit https://github.com/Toufool/Auto-Split/commit/7078b12c36ac428d338e4a70ffd00959bd0ad371 and it will be in v1.4
