### ISSUE TITLE
Feature Request - Pause Timer on Split

### ISSUE THREAD

**Issue by edru** [Toufool/Auto-Split#47]
Games like Sonic the Hedgehog have score counters that are removed for IGT. Is there a way a pause feature could be added? 

Using sonic as an example, have a frame where you hit the sign that would pause the timer, then upon the next start frame, resumes timer.

**Comment by edru** [comment]
Or does the delay function fill this need? Split at end, then it delays the score count.

**Comment by Toufool** [comment]
The delay function only delays the key press of the Split hotkey, it doesn't do any pausing.

Are you trying to use AutoSplit as a load remover only, or a mix of splitting + load removing?

**Comment by edru** [comment]
Some people in the Sonic community were interested in using it as a tool to do RTA minus bonus times for Any% runs. Essentially a pause for XX after split would be sufficient. That way they could hit the end of the level and have it split, then pause for a specified version of time, then start the next split - similar to load removal.

**Comment by Avasam** [comment]
@edru The pause flag {p} from KaDiWa4's fork looks like it feels that need. See PR #50

**Comment by Toufool** [comment]
Pause hotkey and Pause flag have been added in [v1.5](https://github.com/Toufool/Auto-Split/releases/tag/v1.5)
