### ISSUE TITLE
Keep running when reset

### ISSUE THREAD

**Issue by bentglasstube** [Toufool/Auto-Split#48]
I have a configuration for a short speedrun where resets are common that almost works well but having the ability to keep autosplit running when it is reset would make it even better.  I will try to explain the situation so the feature request is understood.

I use autosplit to start the timer as well as to do splits, because there is a consistent image shown at a consistent time before timing starts.  This is set image `001_start#2550#.png` for example.  I want to also have a `reset(0.90).png` file which detects when I reset the game.  Unfortunately, the image I want using for this is the opening title screen of the game.  This means I cannot start the comparisons running because it immediately detects the reset and stops it.

What would be ideal is if there was a way for autosplit to know that I was using it to start the timer and only check for resets when the timer is in the "running" state instead of the "waiting to start" state.  Then timing could be fully automated.

**Comment by Toufool** [comment]
This option has been added in [v1.5](https://github.com/Toufool/Auto-Split/releases/tag/v1.5)
