### ISSUE TITLE
looks weird on a higher res monitor

### ISSUE THREAD

**Issue by undercover-orange** [Toufool/Auto-Split#49]
https://i.imgur.com/AMEq7ig.png

**Comment by flagrama** [comment]
A quick fix for this is to right click the exe, choose properies, go to compatibility tab. On Windows versions prior to some of the latest Windows 10 versions, you can choose to disable DPI scaling. On newer Windows 10 versions you can click the Chagne high DPI settings button and set the scaling override to System.

This is just a workaround for software that doesn't properly support HiDPI display scaling though, so this is still a valid bug IMO.

**Comment by undercover-orange** [comment]
> A quick fix for this is to right click the exe, choose properies, go to compatibility tab. On Windows versions prior to some of the latest Windows 10 versions, you can choose to disable DPI scaling. On newer Windows 10 versions you can click the Chagne high DPI settings button and set the scaling override to System.
> 
> This is just a workaround for software that doesn't properly support HiDPI display scaling though, so this is still a valid bug IMO.

that worked, thank you

**Comment by flagrama** [comment]
This really isn't a proper solution to HiDPI. It's a workaround at best.
