### ISSUE TITLE
undoing a split during the cooldown throws screenshots off by one

### ISSUE THREAD

**Issue by DLH112** [Toufool/Auto-Split#5]
the fadeout entering a boss room was too similar (compared to fadeout after beating said boss) and hit the split, so i pressed the undo split key, which undid the split in livesplit but not autosplit, making livesplit be on split n, but autosplit images be on n+1. I just now realize I could wait for the cooldown to be over before undoing the split as a workaround. So I think undo split (and probably skip split) should override+reset the cooldown.

**Comment by Toufool** [comment]
Nice catch. As you've noted, undo and skip split functionality is disabled when in the paused state. They definitely should override the paused state like the reset button does. Appreciate you pointing that out, and will fix that in a future release.

**Comment by Toufool** [comment]
this bug has been fixed and will be no longer be an issue in the next release.

**Comment by Toufool** [comment]
This has been fixed in [v1.1](https://github.com/Toufool/Auto-Split/releases/tag/v1.1)
