### ISSUE TITLE
Not Loading Pictures + Can't Resize Main Window

### ISSUE THREAD

**Issue by MrTyton** [Toufool/Auto-Split#54]
Hello,

I've got two issues, the first more important than the second.

![image](https://user-images.githubusercontent.com/1666715/103161013-eeab5280-4790-11eb-9cf0-c5e4e586faac.png)

![image](https://user-images.githubusercontent.com/1666715/103161024-126e9880-4791-11eb-9c5f-fc3b315bf3e3.png)

Even though there are images in the folder, no picture is pulled up in the "Current Split Image", so nothing get can be compared against.

Additionally, I can't seem to resize the window, so it makes modifying some of these options rather awkward.

Finally, is it possible to have a "start" image as well as a "loop" image? Or is it tied to just having only "loop"?

Thank you.

**Comment by Toufool** [comment]
which operating system are you on? I've seen the window size issue on windows 8. Also may have to do with the [resolution size of your monitor](https://github.com/Toufool/Auto-Split/issues/49) if you are using a hi-res monitor.

The Current Split Image is only displayed when you click Start Auto Split on the bottom right.

For a start image, you can do just as you are doing there. Just click on Start Auto Split and `001_Start.png` will be the image used to start your timer. Loop images are a separate parameter, using `@@`. For example, if you want to use `002_StageComplete.png` 10 times in a row, you would have edit the file name to `002_@10@_StageComplete.png`

**Comment by MrTyton** [comment]
Win 10. It is a 4k monitor, so that is likely the cause of that.

Hm, I see. Kind of counter intuitive. It also makes it a bit more awkward
to debug though, but I guess that's what I get for missing it.

Hm, I see. I did miss that parameter. My bad. Thank you.

Feel free to close.
