### ISSUE TITLE
LiveSplit won't detect hotkey activation if not focused

### ISSUE THREAD

**Issue by Ofikabacon** [Toufool/Auto-Split#56]
Testing it in Dying Light, if the game is focused when Auto Split activates a split, LiveSplit does not accept it as input. Global Hot Keys is enabled in LiveSplit and the input works fine when pressed physically it just won't receive Auto Split's input unless it is focused. (I have tried multiple different hot keys)

**Comment by Toufool** [comment]
Are you holding a modifier while it is trying to split? Just making sure this is not a duplicate issue of https://github.com/Toufool/Auto-Split/issues/30

**Comment by Ofikabacon** [comment]
Nope, I set it up for cut scenes so there's no chance of accidental additional key presses

**Comment by Toufool** [comment]
What hotkey are you using for your Start / Split hotkey?

**Comment by Ofikabacon** [comment]
I've tried F5, plus, j and comma.

**Comment by Avasam** [comment]
Is your game or livesplit running as administrator by any chance? And does it work if you open all 3 (including AutoSplit) as admin?

**Comment by Avasam** [comment]
I've had this happen recently once in a while during testing. Does not seem like an AutoSplit issue but rather a LiveSplit issue.

When this is happening, I also can't PrtScr with LightShot when focusing LiveSplit, suggesting it's acting exactly like when started as admin.

Apps with Admin privileges won't let other apps catch key events when focused, and they may not catch virtual key events either. This is to be expected as a Windows security feature.
