### ISSUE TITLE
No Images Appear When Selecting A Split Image Folder

### ISSUE THREAD

**Issue by wipeoutjack** [Toufool/Auto-Split#6]
Hey, Im really bad with computers, so its a big possibility im just not understanding something, but when I look for my split image on the autosplitter, i cant find it, and cant find any images at all, just a bunch of empty folders. Sorry if theres a really obvious solution

**Comment by Toufool** [comment]
When you click "browse' the program only allows you to pick a folder, so anything that isn't a folder will not be displayed, but your other files (images) are still there. As long as you have the images in that folder when viewing them in file explorer, you should be able to select that folder and your split images should appear when running the auto splitter.

**Comment by wipeoutjack** [comment]
I got it working! Thanks!
