### ISSUE TITLE
Pause Time can only be integers

### ISSUE THREAD

**Issue by Fencypo** [Toufool/Auto-Split#7]
While testing I found that if I were to be exaggerated with the number of splits, if I put the Pause Time to two seconds it'll split twice during fade out but if I put it to three second it would split late for the next split. 

While not necessarily an issue if you were doing normal splits that splits at a normal point, it would still be good if the Pause Time can be either counted in frames instead of seconds or allow you to use fractions such as 2.3 seconds !

**Comment by Toufool** [comment]
While this is a very specific case, it's easy and fast to change. Will make this change in a future release.

**Comment by Toufool** [comment]
Pause times can now include decimals in [v1.1](https://github.com/Toufool/Auto-Split/releases/tag/v1.1)
