### ISSUE TITLE
Numpad number key with numlock on as split hotkey does not split

### ISSUE THREAD

**Issue by Toufool** [Toufool/Auto-Split#8]
For example: setting the Start / Split key to numpad0 will set it to 0 instead. When a match occurs, it will hit 0 instead of numpad0. The current workaround for this is to turn numlock off when setting your Start / Split hotkey for both AutoSplit and your preferred speedrun timer.

**Comment by Miltrivd** [comment]
Just found the same issue, I want to add that combined hotkeys do not work.

**Example:** I use _CTRL+Numpad*_ for resets to avoid unintended resets.

The key is not registered at all. This happens on any combination, _SHIFT+L_ doesn't result in _L_, it just registers nothing.

**Comment by Toufool** [comment]
I can easily include these. I actually excluded them intentionally just for the purpose of not causing confusion or any bugs with hitting multiple keys. I'll try and include these with the next version.

**Comment by SudoProgramming** [comment]
The use of F13 - F24 also doesn't work, which is gonna be primordially used by foot pedal users or stream deck users.

**Comment by MrGamy** [comment]
@Toufool AutoSplit64 handles splitting completely w/o the global hotkeys but instead utilizes the livesplit.server addon - maybe this could help eliminate the problem?
https://github.com/Kainev/AutoSplit64/blob/master/as64core/livesplit.py

https://github.com/LiveSplit/LiveSplit.Server

**Comment by Avasam** [comment]
@MrGamy  So does KaDiWa's fork (see #50 ). The hotkeys is still an important feature to skip/undo splits and for use outside of LiveSplit. While it wouldn't "eliminate" the problem. I would still love to see AutoSplit use the LiveSplit server in the base fork.

**Comment by Avasam** [comment]
> The use of F13 - F24 also doesn't work, which is gonna be primordially used by foot pedal users or stream deck users.

I can confirm F13-F24 will work in the next version
